// <auto-generated />
using System;
using Dashboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dashboard.Infrastructure.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20260516143115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dashboard.Domain.Entities.HabitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Kind")
                        .IsUnique();

                    b.ToTable("HabitEntries");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.HabitEntry", b =>
                {
                    b.OwnsOne("Dashboard.Domain.ValueObjects.RunningDetails", "Details", b1 =>
                        {
                            b1.Property<int>("HabitEntryId")
                                .HasColumnType("integer");

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("DurationMinutes");

                            b1.Property<decimal>("PaceMinPerKm")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("PaceMinPerKm");

                            b1.HasKey("HabitEntryId");

                            b1.ToTable("HabitEntries");

                            b1.WithOwner()
                                .HasForeignKey("HabitEntryId");
                        });

                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
