// <auto-generated />
using System;
using Dashboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dashboard.Infrastructure.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20260612182503_AddWhoopWorkouts")]
    partial class AddWhoopWorkouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dashboard.Domain.Entities.HabitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Kind")
                        .IsUnique();

                    b.ToTable("HabitEntries");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Strava.RunActivityEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<double[]>("AltitudesMeters")
                        .HasColumnType("double precision[]");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<int[]>("HeartRates")
                        .HasColumnType("integer[]");

                    b.Property<int>("MovingTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<LineString>("Route")
                        .HasColumnType("geometry(LineString, 4326)");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("StreamsFetched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.PrimitiveCollection<int[]>("TimeOffsetsSeconds")
                        .HasColumnType("integer[]");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc");

                    b.HasIndex("StreamsFetched");

                    b.ToTable("RunActivities", (string)null);
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Strava.StravaTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("StravaTokens", (string)null);
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Strava.SyncStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SyncStates", (string)null);
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Whoop.WhoopDailyMetricEntity", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("AwakeHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("DayStrain")
                        .HasColumnType("double precision");

                    b.Property<double?>("DeepSleepHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("HrvMillis")
                        .HasColumnType("double precision");

                    b.Property<double?>("LightSleepHours")
                        .HasColumnType("double precision");

                    b.Property<int?>("RecoveryScore")
                        .HasColumnType("integer");

                    b.Property<double?>("RemSleepHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("RespiratoryRate")
                        .HasColumnType("double precision");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("SkinTempCelsius")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("SleepEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SleepHours")
                        .HasColumnType("double precision");

                    b.Property<int?>("SleepPerformance")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SleepStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Spo2Percentage")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Date");

                    b.ToTable("WhoopDailyMetrics", (string)null);
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Whoop.WhoopProcessedWorkoutEntity", b =>
                {
                    b.Property<string>("WorkoutId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkoutId");

                    b.ToTable("WhoopProcessedWorkouts", (string)null);
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Whoop.WhoopTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WhoopTokens", (string)null);
                });

            modelBuilder.Entity("Dashboard.Infrastructure.Whoop.WhoopWorkoutEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("HighIntensityShare")
                        .HasColumnType("double precision");

                    b.Property<double?>("Kilojoule")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Strain")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Zone0Milli")
                        .HasColumnType("bigint");

                    b.Property<long?>("Zone1Milli")
                        .HasColumnType("bigint");

                    b.Property<long?>("Zone2Milli")
                        .HasColumnType("bigint");

                    b.Property<long?>("Zone3Milli")
                        .HasColumnType("bigint");

                    b.Property<long?>("Zone4Milli")
                        .HasColumnType("bigint");

                    b.Property<long?>("Zone5Milli")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc");

                    b.ToTable("WhoopWorkouts", (string)null);
                });

            modelBuilder.Entity("EmomSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmomWorkoutId")
                        .HasColumnType("integer");

                    b.Property<int>("FromMinute")
                        .HasColumnType("integer");

                    b.Property<int>("PullupsPerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("PushupsPerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("ToMinute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmomWorkoutId");

                    b.ToTable("EmomSegment");
                });

            modelBuilder.Entity("EmomWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HabitEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitEntryId")
                        .IsUnique();

                    b.ToTable("EmomWorkout");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.HabitEntry", b =>
                {
                    b.OwnsOne("Dashboard.Domain.ValueObjects.RunningDetails", "Running", b1 =>
                        {
                            b1.Property<int>("HabitEntryId")
                                .HasColumnType("integer");

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("DurationMinutes");

                            b1.Property<decimal>("PaceMinPerKm")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("PaceMinPerKm");

                            b1.HasKey("HabitEntryId");

                            b1.ToTable("HabitEntries");

                            b1.WithOwner()
                                .HasForeignKey("HabitEntryId");
                        });

                    b.Navigation("Running");
                });

            modelBuilder.Entity("EmomSegment", b =>
                {
                    b.HasOne("EmomWorkout", null)
                        .WithMany("Segments")
                        .HasForeignKey("EmomWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmomWorkout", b =>
                {
                    b.HasOne("Dashboard.Domain.Entities.HabitEntry", null)
                        .WithOne("Emom")
                        .HasForeignKey("EmomWorkout", "HabitEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.HabitEntry", b =>
                {
                    b.Navigation("Emom");
                });

            modelBuilder.Entity("EmomWorkout", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
